//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cofe_Manager_.Data_acces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B_machinecafeEntities : DbContext
    {
        public B_machinecafeEntities()
            : base("name=B_machinecafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_boisson> T_boisson { get; set; }
        public virtual DbSet<T_selection> T_selection { get; set; }
        public virtual DbSet<T_badge> T_badge { get; set; }
    }
}
