//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cofe_Manager_.Data_acces
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_boisson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_boisson()
        {
            this.T_selection = new HashSet<T_selection>();
        }
    
        public int id_boisson { get; set; }
        public string libelle_b { get; set; }
        public Nullable<int> Qte_sucre_recommandation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_selection> T_selection { get; set; }
    }
}
