//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cofe_Manager_.Data_acces
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_selection
    {
        public int id_selection { get; set; }
        public Nullable<int> qte_sucre { get; set; }
        public Nullable<int> id_boisson { get; set; }
        public Nullable<int> id_badge { get; set; }
        public Nullable<bool> mug { get; set; }
    
        public virtual T_boisson T_boisson { get; set; }
        public virtual T_badge T_badge { get; set; }
    }
}
