USE [master]
GO

/****** Object:  Database [B_machinecafe]    Script Date: 06/09/2019 14:53:59 ******/
CREATE DATABASE [B_machinecafe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'B_machinecafe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\B_machinecafe.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'B_machinecafe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\B_machinecafe_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [B_machinecafe] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [B_machinecafe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [B_machinecafe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [B_machinecafe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [B_machinecafe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [B_machinecafe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [B_machinecafe] SET ARITHABORT OFF 
GO

ALTER DATABASE [B_machinecafe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [B_machinecafe] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [B_machinecafe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [B_machinecafe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [B_machinecafe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [B_machinecafe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [B_machinecafe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [B_machinecafe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [B_machinecafe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [B_machinecafe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [B_machinecafe] SET  ENABLE_BROKER 
GO

ALTER DATABASE [B_machinecafe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [B_machinecafe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [B_machinecafe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [B_machinecafe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [B_machinecafe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [B_machinecafe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [B_machinecafe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [B_machinecafe] SET RECOVERY FULL 
GO

ALTER DATABASE [B_machinecafe] SET  MULTI_USER 
GO

ALTER DATABASE [B_machinecafe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [B_machinecafe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [B_machinecafe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [B_machinecafe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [B_machinecafe] SET  READ_WRITE 
GO

